server:
  port: 7777

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/cloud-user/**
          filters:
            - RewritePath=/cloud-user/(?<path>/?.*), /$\{path}
          uri: http://localhost:8084
          #uri: lb://ms_user

        - id: route2
          predicates:
            - Path=/cloud-server/**
          filters:
            - RewritePath=/cloud-server/(?<path>/?.*), /$\{path}
          uri: http://localhost:8085





